#!/usr/bin/env bash
#  OKUSON Package
#  Frank Lübeck and Max Neunhöffer

# This little script helps to calculate encrypted administrator passwords.
python2 << TOEND

import getpass,crypt,random,time,sys,os

# read salt mask from Config.xml
homedir = os.path.abspath(sys.path[0])
os.chdir(os.path.join(homedir,"server"))
import Config
Config.ReadConfig()
import WebWorkers

print __doc__,"\n\nPlease enter a password to encrypt:"
p = getpass.getpass("Password: ")
p2 = getpass.getpass("Again: ")
if p != p2:
    print "Passwords are not identical! Aborting."
    sys.exit(0)

random.seed(time.time());
s = WebWorkers.MakeHashSalt()
c = crypt.crypt(p,s)
print "Encrypted password:",c
TOEND
