#!/bin/sh
# Part of the OKUSON project
# Copyright (C) 2003-2016 by Frank Lübeck and Max Neunhöffer

# This script is used to make a zipped tar archive with the distribution
# and a pdf version of the manual outside this directory. For this
# purpose the whole git repository should be exported and this script be run
# in this exported directory.

# Delete the internal examples and test tools:
rm -rf test

# Make the manual:
cd doc
pdflatex manual
pdflatex manual
pdflatex manual
rm -f manual.toc manual.aux manual.out manual.log
cd ..

# Copy it outside:
cp doc/manual.pdf ../okuson-`cat VERSION`.pdf

# Move the configuration file and the web page templates from "html" to
# "html.sample":
mv Config.xml Config.xml.sample
mv html html.sample
mkdir html
mkdir html/images

# Cut the log file and throw away project devel/selling utilities
rm -rf log/server.log website poster HOWTORELEASE TODO `find . -name .git`
# new archives should not override log files:   touch log/server.log

# Release only empty files:
cd data
rm -f examregistrations.txt generalmessage.txt homework.txt people.txt \
      exams.txt groups.txt messages.txt submissions.txt groupinfo.txt
cd ..

# Copy example sheet B0 to the sheets and exercise directories:
#cp examples/exercises/B0* exercises
#cp examples/sheets/B0.bla sheets

# Make sure a temporary directory is there:
if [ ! -x tmp ]; then
  mkdir tmp
fi

# Delete ourselves:
rm -f makeArchive

# Now put together things:
cd ..
mv OKUSON okuson
tar czvf okuson-`cat okuson/VERSION`.tar.gz --exclude='.nfs*' okuson

