#!/usr/bin/env python

import sys,os,time

homedir = os.path.abspath(sys.path[0])
os.environ["OKUSONHOME"] = homedir

pid = os.fork()
if pid == 0:
    time.sleep(0.1)   # Let the parent get hold of the log file
    server = os.path.join(homedir,"server/Server.py")
    os.execl(server,server)

f = file("log/server.log","r")
f.seek(0,2)     # seek to end of file
p = f.tell()

ok = 0
while 1:
    f.seek(0,2)
    np = f.tell()
    if np > p:
        f.seek(p)
        s = f.readlines()
        p = f.tell()
        for l in s:
            if l[:29] == 'Error:  Cannot start service!':
                sys.stdout.write(l)
                sys.exit(1)
            elif ok:
                sys.exit(0)
            elif l[-27:] == 'Ready to start service ...\n':
                sys.stdout.write(l)
                ok = 1
                s = s+f.readlines()
                if l == s[-1]:
                    sys.exit(0)
            elif l == 'Aborting.\n':
                sys.stdout.write(l)
                sys.exit(0)
    time.sleep(0.5)

