#!/usr/bin/env python

import sys,os,time

homedir = os.path.abspath(sys.path[0])
os.environ["OKUSONHOME"] = homedir

pid = os.fork()
if pid == 0:
    time.sleep(0.1)   # Let the parent get hold of the log file
    server = os.path.join(homedir,"server/Server.py")
    os.execl(server,server)

# no longer necessary:
#f = file("currentPID", "w")
#f.write(str(pid))
#f.close

f = file("log/server.log","r")
f.seek(0,2)     # seek to end of file
p = f.tell()

while 1:
    f.seek(0,2)
    np = f.tell()
    if np > p:
        f.seek(p)
        s = f.readlines()
        p = f.tell()
        for l in s:
            sys.stdout.write(l)
            if l[-25:] == 'Server up and running...\n':
                sys.exit(0)
            elif l == 'Aborting.\n':
                sys.exit(0)
    time.sleep(0.5)
