#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
#
#   Copyright (C) 2003 by  Frank Lübeck  and   Max Neunhöffer
#
'''Stop the OKUSON server and show logfile line until all threads have
terminated.'''

import sys,os,time

homedir = os.path.abspath(sys.path[0])
os.environ["OKUSONHOME"] = homedir
os.chdir(homedir)

realprog = os.path.join(homedir,"server/Stop.py")
os.execl(realprog,realprog)
