#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
#
#   Copyright (C) 2003 by  Frank Lübeck  and   Max Neunhöffer
#
#   $Id: stop,v 1.2 2003/10/03 00:07:00 luebeck Exp $
'''Stop the OKUSON server and show logfile line until all threads have
terminated.'''

import sys,os,time

homedir = os.path.abspath(sys.path[0])
os.environ["OKUSONHOME"] = homedir

realprog = os.path.join(homedir,"server/Stop.py")
os.execl(realprog,realprog)
