#!/usr/bin/env python2
# -*- coding: ISO-8859-1 -*-
#
#   Copyright (C) 2003 by  Frank Lübeck  and   Max Neunhöffer
#
'''Test sheet files (.bla), produces a .tex file with all exercises and
questions in layout from OKUSON configuration. Appends solution of
interactive exercises.
'''

import sys,os,time

homedir = os.path.abspath(sys.path[0])
os.environ["OKUSONHOME"] = homedir

realprog = os.path.join(homedir,"server/TestSheet.py")
args = list(sys.argv)
args[0] = realprog
os.execv(realprog,args)
