#!/usr/bin/env python

import sys,os,time

homedir = os.path.abspath(sys.path[0])
os.environ["OKUSONHOME"] = homedir

realprog = os.path.join(homedir,"server/TestSheet.py")
args = list(sys.argv)
args[0] = realprog
os.execv(realprog,args)
