#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
#
#   Copyright (C) 2003 by  Frank Lübeck  and   Max Neunhöffer
#
'''Test exercise files (.tex and .auf), produce images corresponding
to layout in OKUSON configuration.'''

import sys,os,time

homedir = os.path.abspath(sys.path[0])
os.environ["OKUSONHOME"] = homedir

realprog = os.path.join(homedir,"server/TestExercise.py")
args = list(sys.argv)
args[0] = realprog
os.execv(realprog,args)
