#!/usr/bin/env    python
# -*- coding: ISO-8859-1 -*-
#
#   Copyright (C) 2003 by  Frank Lübeck  and   Max Neunhöffer
#
#   $Id: xmlvalidate,v 1.2 2003/11/11 09:46:50 luebeck Exp $

import os, sys
sys.path = [os.path.join(sys.path[0], 'server')] + sys.path
from fmTools import Utils, XMLRewrite

if len(sys.argv) == 1:
  print '''Usage:    xmlvalidate [-w] file1 [file2] [...]

With -w option it is checked if the file is a well formed XML document.
'''

action = 'Validating'
if '-w' in sys.argv:
  XMLRewrite.ValidatingParserConfig['NoNoDTDWarning'] = 1
  XMLRewrite.ValidatingParserConfig['Validate'] = 0
  action = 'Checking'
  
files = sys.argv[1:]
for fn in files:
  if fn == '-w':
    pass
  elif not os.path.exists(fn):
    Utils.Error('File '+fn+' does not exist.')
  else:
    Utils.Error(action+' file '+fn+' ...', prefix='')
    t = XMLRewrite.Parse(config=XMLRewrite.ValidatingParserConfig, file=fn)
    if t: 
      Utils.Error('Success!', prefix='')
