#!/usr/bin/env    python
# -*- coding: ISO-8859-1 -*-
#
#   Copyright (C) 2003 by  Frank Lübeck  and   Max Neunhöffer
#
#   $Id: xmlvalidate,v 1.1 2003/10/06 18:35:46 luebeck Exp $

import os, sys
sys.path = [os.path.join(sys.path[0], 'server')] + sys.path
from fmTools import Utils, XMLRewrite

if len(sys.argv) == 1:
  print '''Usage:    xmlvalidate [-w] file1 [file2] [...]

With -w option it is checked if the file is a well formed XML document.
'''

action = 'Validating'
if '-w' in sys.argv:
  XMLRewrite.ValidatingParser.NoNoDTDWarning = 1
  XMLRewrite.Validate = 0
  action = 'Checking'
  
files = sys.argv[1:]
for fn in files:
  if fn == '-w':
    pass
  elif not os.path.exists(fn):
    Utils.Error('File '+fn+' does not exist.')
  else:
    Utils.Error(action+' file '+fn+' ...', prefix='')
    try:
      t = None
      t = XMLRewrite.ValidateXMLFile(fn)
      if t: Utils.Error('Success!', prefix='')
    except:
      pass 
