#!/bin/sh
##  okusonsync       syncronizes an OKUSON installation using rsync

BACKUPDIR="..."
ORIGSERVER="..."
ORIGDIR="..."  # no final '/'

cd $BACKUPDIR
rsync -a --delete -e ssh $ORIGSERVER:$ORIGDIR .

